-- Dados do módulo de cortes vindos da planilha 'Marcelo - 22.09.26' (abas Material, Resumo e Calc).
-- Rode DEPOIS do cortes.sql. Pode rodar de novo: não duplica nada.
begin;

insert into cores (nome) values
  ('Preto'),
  ('Satin'),
  ('Chocolate'),
  ('Chumbo'),
  ('Sanremo'),
  ('Odalisca'),
  ('Vermelho'),
  ('Sandia'),
  ('Callas')
on conflict (nome) do nothing;

insert into insumos (nome, unidade_consumo, unidade_compra, fator, multiplo, por_cor) values
  ('Alça de coraçãozinho', 'un', 'Pares', 2, 50, true),
  ('Alça de sutiã', 'm', 'Metros', 1, 50, true),
  ('Alça de sutiã pronta', 'un', 'Pares', 2, 50, true),
  ('Arco', 'un', 'Un', 1, 1, true),
  ('Argola', 'un', 'Un', 1, 1, true),
  ('Bojo Casca', 'un', 'Pares', 2, 50, true),
  ('Elástico Cru (tapioca) 24 mm', 'm', 'Metros', 1, null, true),
  ('Elástico Cru (tapioca) 25 mm', 'm', 'Metros', 1, null, true),
  ('Elástico primavera', 'm', 'Rolos', 50, 1, true),
  ('Elástico Savana 12mm', 'm', 'Rolos', 100, 1, false),
  ('Elástico Savana 15mm', 'm', 'Rolos', 100, 1, false),
  ('Elástico Taquara', 'm', 'Rolos', 50, 1, true),
  ('Elástico Viés 16 mm', 'm', 'Rolos', 100, 1, true),
  ('Elástico Viés 25 mm', 'm', 'Rolos', 50, 1, true),
  ('Fecho Sutiã', 'un', 'Un', 1, 1, true),
  ('Fio overlock', 'un', 'Un', 1, 1, true),
  ('Forro', 'kg', 'Kg', 1, 0.5, true),
  ('Laço grande', 'un', 'Un', 1, 1, true),
  ('Linha', 'un', 'Un', 1, 1, true),
  ('Microfibra de Poliamida', 'kg', 'Kg', 1, 1, true),
  ('Pino tag', 'un', 'Un', 1, 1, true),
  ('Renda', 'm', 'Rolos', 112.5, 1, true),
  ('Renda 5 cm', 'm', 'Metros', 1, null, true),
  ('Renda com fio dourado', 'm', 'Rolos', 112.5, 1, true),
  ('Renda estreita', 'm', 'Rolos', 270, 1, true),
  ('Renda Neon', 'm', 'Rolos', 112.5, 1, true),
  ('Rendão', 'kg', 'Kg', 1, 0.1, true),
  ('Suede', 'kg', 'Kg', 1, 0.1, true),
  ('Tule', 'kg', 'Kg', 1, 0.1, true),
  ('Coração passante triplo', 'un', 'Un', 1, 1, true),
  ('Coelho passante triplo', 'un', 'Un', 1, 1, true),
  ('Coração Faz o Pix', 'un', 'Un', 1, 1, true)
on conflict (nome) do nothing;

insert into modelos (nome, tipo)
select v.nome, v.tipo from (values
  ('Fábia', 'Calcinha'),
  ('Gabi', 'Calcinha'),
  ('Adri', 'Calcinha'),
  ('Waléria', 'Calcinha'),
  ('Sarah', 'Calcinha'),
  ('Letícia', 'Calcinha'),
  ('Bel', 'Calcinha'),
  ('Fábia Tule', 'Calcinha'),
  ('Jade', 'Calcinha'),
  ('Flor', 'Calcinha'),
  ('Flor - Microfibra', 'Calcinha'),
  ('Vivi', 'Calcinha'),
  ('Bia', 'Calcinha'),
  ('Rubi', 'Calcinha'),
  ('Sol', 'Calcinha'),
  ('Lua', 'Calcinha'),
  ('Diamante', 'Calcinha'),
  ('Estrela', 'Calcinha'),
  ('Conjunto Victória', 'Conjunto'),
  ('Conjunto Beatriz', 'Conjunto'),
  ('Conjunto Flor', 'Conjunto'),
  ('Conjunto Adri', 'Conjunto'),
  ('Conjunto Letícia', 'Conjunto'),
  ('Conjunto Riana', 'Conjunto'),
  ('Letícia Suede', 'Calcinha'),
  ('Riana Microfibra', 'Calcinha'),
  ('Riana Renda', 'Calcinha'),
  ('Sorvete', 'Calcinha'),
  ('Larah', 'Calcinha'),
  ('Pérola', 'Calcinha'),
  ('Esther', 'Calcinha'),
  ('Estela', 'Calcinha'),
  ('Luana', 'Calcinha'),
  ('Mara', 'Calcinha'),
  ('Laura', 'Calcinha'),
  ('Gigi', 'Calcinha'),
  ('Conjunto Orquídea', 'Conjunto'),
  ('Encanto', 'Calcinha'),
  ('Paixão', 'Calcinha'),
  ('Body Sedução', 'Body'),
  ('Chamego', 'Calcinha'),
  ('Sonho', 'Calcinha'),
  ('Alegria', 'Calcinha'),
  ('Daniella', 'Calcinha'),
  ('Bella', 'Calcinha'),
  ('Conjunto Lírio', 'Conjunto'),
  ('Conjunto Tulipa', 'Conjunto'),
  ('Márcia', 'Calcinha'),
  ('Bianca', 'Calcinha'),
  ('Núvem', 'Calcinha'),
  ('Cristal', 'Calcinha'),
  ('Turquesa', 'Calcinha'),
  ('Carinho', 'Calcinha'),
  ('Amor', 'Calcinha'),
  ('Desejo', 'Calcinha'),
  ('Ana', 'Calcinha'),
  ('Kamila', 'Calcinha'),
  ('Coração', 'Calcinha'),
  ('Núbia', 'Calcinha'),
  ('Meirinha', 'Calcinha'),
  ('Natália', 'Calcinha'),
  ('Laura Suede', 'Calcinha'),
  ('Charme', 'Calcinha'),
  ('Eclipse', 'Calcinha'),
  ('Safira', 'Calcinha'),
  ('Cupido', 'Calcinha'),
  ('Selvagem', 'Calcinha'),
  ('Atrevida', 'Calcinha')
) v(nome, tipo)
where not exists (select 1 from modelos m where lower(m.nome) = lower(v.nome));

insert into ficha_tecnica (modelo_id, insumo_id, consumo)
select m.id, i.id, v.consumo from (values
  ('Fábia', 'Elástico Cru (tapioca) 24 mm', 0.8),
  ('Fábia', 'Elástico Viés 16 mm', 1.1),
  ('Fábia', 'Fio overlock', 0.015),
  ('Fábia', 'Forro', 0.0018),
  ('Fábia', 'Pino tag', 1.0),
  ('Fábia', 'Linha', 0.02),
  ('Fábia', 'Microfibra de Poliamida', 0.026),
  ('Gabi', 'Elástico Viés 25 mm', 0.8),
  ('Gabi', 'Elástico Viés 16 mm', 0.7),
  ('Gabi', 'Microfibra de Poliamida', 0.03),
  ('Gabi', 'Forro', 0.0018),
  ('Gabi', 'Pino tag', 1.0),
  ('Gabi', 'Linha', 0.02),
  ('Gabi', 'Fio overlock', 0.015),
  ('Adri', 'Alça de sutiã pronta', 2.0),
  ('Adri', 'Elástico Viés 16 mm', 0.9),
  ('Adri', 'Fio overlock', 0.015),
  ('Adri', 'Forro', 0.0015),
  ('Adri', 'Elástico primavera', 0.25),
  ('Adri', 'Linha', 0.02),
  ('Adri', 'Microfibra de Poliamida', 0.006),
  ('Adri', 'Pino tag', 1.0),
  ('Adri', 'Renda', 0.2),
  ('Waléria', 'Fio overlock', 0.015),
  ('Waléria', 'Forro', 0.002),
  ('Waléria', 'Linha', 0.02),
  ('Waléria', 'Microfibra de Poliamida', 0.015),
  ('Waléria', 'Pino tag', 1.0),
  ('Waléria', 'Renda', 0.914),
  ('Sarah', 'Elástico Viés 16 mm', 0.4),
  ('Sarah', 'Elástico Viés 25 mm', 0.8),
  ('Sarah', 'Fio overlock', 0.015),
  ('Sarah', 'Forro', 0.002),
  ('Sarah', 'Pino tag', 1.0),
  ('Sarah', 'Linha', 0.02),
  ('Sarah', 'Microfibra de Poliamida', 0.05),
  ('Letícia', 'Fio overlock', 0.015),
  ('Letícia', 'Forro', 0.0018),
  ('Letícia', 'Linha', 0.02),
  ('Letícia', 'Microfibra de Poliamida', 0.022),
  ('Letícia', 'Renda estreita', 1.9),
  ('Letícia', 'Pino tag', 1.0),
  ('Bel', 'Elástico primavera', 0.35),
  ('Bel', 'Elástico Viés 16 mm', 0.7),
  ('Bel', 'Elástico Viés 25 mm', 0.4),
  ('Bel', 'Fio overlock', 0.015),
  ('Bel', 'Forro', 0.0018),
  ('Bel', 'Linha', 0.02),
  ('Bel', 'Renda', 0.3),
  ('Bel', 'Pino tag', 1.0),
  ('Bel', 'Tule', 0.01),
  ('Fábia Tule', 'Elástico Cru (tapioca) 25 mm', 0.8),
  ('Fábia Tule', 'Elástico Viés 16 mm', 1.1),
  ('Fábia Tule', 'Fio overlock', 0.015),
  ('Fábia Tule', 'Forro', 0.0018),
  ('Fábia Tule', 'Pino tag', 1.0),
  ('Fábia Tule', 'Linha', 0.02),
  ('Fábia Tule', 'Tule', 0.013),
  ('Jade', 'Alça de sutiã pronta', 2.0),
  ('Jade', 'Elástico Viés 16 mm', 0.35),
  ('Jade', 'Fio overlock', 0.015),
  ('Jade', 'Forro', 0.002),
  ('Jade', 'Pino tag', 1.0),
  ('Jade', 'Linha', 0.02),
  ('Jade', 'Renda', 0.62),
  ('Flor', 'Alça de sutiã pronta', 2.0),
  ('Flor', 'Elástico Viés 16 mm', 1.1),
  ('Flor', 'Fio overlock', 0.015),
  ('Flor', 'Forro', 0.002),
  ('Flor', 'Linha', 0.02),
  ('Flor', 'Elástico primavera', 0.2),
  ('Flor', 'Tule', 0.005),
  ('Flor', 'Pino tag', 1.0),
  ('Flor', 'Renda', 0.2),
  ('Flor - Microfibra', 'Elástico Viés 25 mm', 0.8),
  ('Flor - Microfibra', 'Elástico Viés 16 mm', 0.6),
  ('Flor - Microfibra', 'Fio overlock', 0.015),
  ('Flor - Microfibra', 'Forro', 0.002),
  ('Flor - Microfibra', 'Pino tag', 1.0),
  ('Flor - Microfibra', 'Linha', 0.02),
  ('Flor - Microfibra', 'Microfibra de Poliamida', 0.018),
  ('Vivi', 'Fio overlock', 0.015),
  ('Vivi', 'Forro', 0.002),
  ('Vivi', 'Pino tag', 1.0),
  ('Vivi', 'Linha', 0.02),
  ('Vivi', 'Renda', 1.3),
  ('Bia', 'Elástico Viés 25 mm', 0.8),
  ('Bia', 'Fio overlock', 0.015),
  ('Bia', 'Forro', 0.002),
  ('Bia', 'Pino tag', 1.0),
  ('Bia', 'Linha', 0.02),
  ('Bia', 'Renda', 0.78),
  ('Rubi', 'Elástico Viés 25 mm', 0.8),
  ('Rubi', 'Elástico Viés 16 mm', 0.7),
  ('Rubi', 'Tule', 0.016),
  ('Rubi', 'Forro', 0.0018),
  ('Rubi', 'Pino tag', 1.0),
  ('Rubi', 'Linha', 0.02),
  ('Rubi', 'Fio overlock', 0.015),
  ('Sol', 'Alça de sutiã pronta', 2.0),
  ('Sol', 'Elástico primavera', 0.2),
  ('Sol', 'Elástico Viés 16 mm', 0.9),
  ('Sol', 'Fio overlock', 0.015),
  ('Sol', 'Forro', 0.002),
  ('Sol', 'Pino tag', 1.0),
  ('Sol', 'Linha', 0.02),
  ('Sol', 'Renda', 0.3),
  ('Lua', 'Alça de sutiã pronta', 2.0),
  ('Lua', 'Elástico Viés 16 mm', 0.9),
  ('Lua', 'Fio overlock', 0.015),
  ('Lua', 'Forro', 0.002),
  ('Lua', 'Pino tag', 1.0),
  ('Lua', 'Linha', 0.02),
  ('Lua', 'Renda', 0.2),
  ('Diamante', 'Alça de sutiã pronta', 2.0),
  ('Diamante', 'Elástico Viés 16 mm', 0.9),
  ('Diamante', 'Fio overlock', 0.015),
  ('Diamante', 'Forro', 0.002),
  ('Diamante', 'Pino tag', 1.0),
  ('Diamante', 'Linha', 0.02),
  ('Diamante', 'Tule', 0.008),
  ('Estrela', 'Elástico primavera', 0.2),
  ('Estrela', 'Elástico Viés 16 mm', 1.8),
  ('Estrela', 'Fio overlock', 0.01),
  ('Estrela', 'Forro', 0.002),
  ('Estrela', 'Pino tag', 1.0),
  ('Estrela', 'Linha', 0.016),
  ('Estrela', 'Microfibra de Poliamida', 0.007),
  ('Estrela', 'Renda', 0.17),
  ('Conjunto Victória', 'Alça de sutiã pronta', 2.0),
  ('Conjunto Victória', 'Elástico Viés 25 mm', 0.9),
  ('Conjunto Victória', 'Fio overlock', 0.03),
  ('Conjunto Victória', 'Forro', 0.0018),
  ('Conjunto Victória', 'Pino tag', 1.0),
  ('Conjunto Victória', 'Linha', 0.06),
  ('Conjunto Victória', 'Renda', 2.8),
  ('Conjunto Beatriz', 'Alça de sutiã pronta', 2.0),
  ('Conjunto Beatriz', 'Elástico primavera', 0.8),
  ('Conjunto Beatriz', 'Elástico Viés 25 mm', 2.0),
  ('Conjunto Beatriz', 'Fio overlock', 0.01),
  ('Conjunto Beatriz', 'Pino tag', 1.0),
  ('Conjunto Beatriz', 'Linha', 0.016),
  ('Conjunto Beatriz', 'Microfibra de Poliamida', 0.016),
  ('Conjunto Beatriz', 'Renda', 2.1),
  ('Conjunto Flor', 'Alça de sutiã pronta', 4.0),
  ('Conjunto Flor', 'Elástico primavera', 0.25),
  ('Conjunto Flor', 'Alça de sutiã', 0.7),
  ('Conjunto Flor', 'Elástico Viés 16 mm', 1.1),
  ('Conjunto Flor', 'Forro', 0.002),
  ('Conjunto Flor', 'Elástico Viés 25 mm', 0.35),
  ('Conjunto Flor', 'Fio overlock', 0.01),
  ('Conjunto Flor', 'Pino tag', 1.0),
  ('Conjunto Flor', 'Linha', 0.016),
  ('Conjunto Flor', 'Tule', 0.012),
  ('Conjunto Flor', 'Renda', 0.65),
  ('Conjunto Adri', 'Alça de sutiã pronta', 4.0),
  ('Conjunto Adri', 'Elástico primavera', 0.25),
  ('Conjunto Adri', 'Alça de sutiã', 0.7),
  ('Conjunto Adri', 'Elástico Viés 16 mm', 1.1),
  ('Conjunto Adri', 'Forro', 0.002),
  ('Conjunto Adri', 'Elástico Viés 25 mm', 0.35),
  ('Conjunto Adri', 'Fio overlock', 0.01),
  ('Conjunto Adri', 'Pino tag', 1.0),
  ('Conjunto Adri', 'Linha', 0.016),
  ('Conjunto Adri', 'Tule', 0.012),
  ('Conjunto Adri', 'Renda', 0.65),
  ('Conjunto Letícia', 'Alça de sutiã pronta', 2.0),
  ('Conjunto Letícia', 'Renda estreita', 3.6),
  ('Conjunto Letícia', 'Elástico Viés 25 mm', 0.8),
  ('Conjunto Letícia', 'Fio overlock', 0.01),
  ('Conjunto Letícia', 'Forro', 0.002),
  ('Conjunto Letícia', 'Pino tag', 1.0),
  ('Conjunto Letícia', 'Linha', 0.016),
  ('Conjunto Letícia', 'Tule', 0.028),
  ('Conjunto Riana', 'Alça de sutiã pronta', 2.0),
  ('Conjunto Riana', 'Renda 5 cm', 1.7),
  ('Conjunto Riana', 'Renda', 1.48),
  ('Conjunto Riana', 'Fio overlock', 0.01),
  ('Conjunto Riana', 'Forro', 0.002),
  ('Conjunto Riana', 'Pino tag', 1.0),
  ('Conjunto Riana', 'Linha', 0.016),
  ('Letícia Suede', 'Suede', 0.037),
  ('Letícia Suede', 'Renda estreita', 2.0),
  ('Letícia Suede', 'Fio overlock', 0.01),
  ('Letícia Suede', 'Forro', 0.002),
  ('Letícia Suede', 'Pino tag', 1.0),
  ('Letícia Suede', 'Linha', 0.016),
  ('Riana Microfibra', 'Elástico Viés 16 mm', 0.4),
  ('Riana Microfibra', 'Fio overlock', 0.01),
  ('Riana Microfibra', 'Forro', 0.002),
  ('Riana Microfibra', 'Pino tag', 1.0),
  ('Riana Microfibra', 'Linha', 0.016),
  ('Riana Microfibra', 'Microfibra de Poliamida', 0.017),
  ('Riana Microfibra', 'Renda 5 cm', 0.8),
  ('Riana Renda', 'Renda', 0.56),
  ('Riana Renda', 'Renda 5 cm', 0.8),
  ('Riana Renda', 'Fio overlock', 0.01),
  ('Riana Renda', 'Forro', 0.002),
  ('Riana Renda', 'Pino tag', 1.0),
  ('Riana Renda', 'Linha', 0.016),
  ('Sorvete', 'Renda 5 cm', 1.6),
  ('Sorvete', 'Fio overlock', 0.01),
  ('Sorvete', 'Forro', 0.002),
  ('Sorvete', 'Pino tag', 1.0),
  ('Sorvete', 'Linha', 0.016),
  ('Larah', 'Fio overlock', 0.015),
  ('Larah', 'Forro', 0.0018),
  ('Larah', 'Linha', 0.02),
  ('Larah', 'Microfibra de Poliamida', 0.025),
  ('Larah', 'Renda estreita', 2.0),
  ('Larah', 'Pino tag', 1.0),
  ('Pérola', 'Alça de sutiã pronta', 4.0),
  ('Pérola', 'Elástico primavera', 0.2),
  ('Pérola', 'Elástico Viés 16 mm', 0.9),
  ('Pérola', 'Fio overlock', 0.015),
  ('Pérola', 'Forro', 0.0018),
  ('Pérola', 'Pino tag', 1.0),
  ('Pérola', 'Linha', 0.02),
  ('Pérola', 'Renda', 0.7),
  ('Esther', 'Elástico primavera', 0.2),
  ('Esther', 'Elástico Savana 15mm', 0.4),
  ('Esther', 'Elástico Viés 16 mm', 0.65),
  ('Esther', 'Fio overlock', 0.015),
  ('Esther', 'Forro', 0.0018),
  ('Esther', 'Linha', 0.02),
  ('Esther', 'Microfibra de Poliamida', 0.016),
  ('Esther', 'Pino tag', 1.0),
  ('Esther', 'Renda', 0.18),
  ('Estela', 'Renda 5 cm', 0.8),
  ('Estela', 'Elástico Viés 16 mm', 1.1),
  ('Estela', 'Fio overlock', 0.015),
  ('Estela', 'Forro', 0.0018),
  ('Estela', 'Pino tag', 1.0),
  ('Estela', 'Linha', 0.02),
  ('Estela', 'Microfibra de Poliamida', 0.026),
  ('Luana', 'Elástico Viés 25 mm', 0.7),
  ('Luana', 'Fio overlock', 0.015),
  ('Luana', 'Forro', 0.0018),
  ('Luana', 'Elástico Viés 16 mm', 1.1),
  ('Luana', 'Linha', 0.02),
  ('Luana', 'Microfibra de Poliamida', 0.025),
  ('Luana', 'Pino tag', 1.0),
  ('Luana', 'Renda', 0.17),
  ('Mara', 'Elástico Viés 16 mm', 1.5),
  ('Mara', 'Fio overlock', 0.015),
  ('Mara', 'Forro', 0.0018),
  ('Mara', 'Pino tag', 1.0),
  ('Mara', 'Linha', 0.02),
  ('Mara', 'Microfibra de Poliamida', 0.037),
  ('Laura', 'Elástico Viés 16 mm', 1.2),
  ('Laura', 'Elástico Viés 25 mm', 0.8),
  ('Laura', 'Fio overlock', 0.015),
  ('Laura', 'Forro', 0.0018),
  ('Laura', 'Pino tag', 1.0),
  ('Laura', 'Linha', 0.02),
  ('Laura', 'Microfibra de Poliamida', 0.04),
  ('Gigi', 'Elástico primavera', 0.15),
  ('Gigi', 'Elástico Viés 25 mm', 1.4),
  ('Gigi', 'Fio overlock', 0.015),
  ('Gigi', 'Forro', 0.0018),
  ('Gigi', 'Pino tag', 1.0),
  ('Gigi', 'Linha', 0.02),
  ('Gigi', 'Microfibra de Poliamida', 0.028),
  ('Gigi', 'Renda', 0.17),
  ('Conjunto Orquídea', 'Alça de sutiã pronta', 2.0),
  ('Conjunto Orquídea', 'Arco', 2.0),
  ('Conjunto Orquídea', 'Elástico primavera', 1.2),
  ('Conjunto Orquídea', 'Elástico Taquara', 0.7),
  ('Conjunto Orquídea', 'Elástico Viés 16 mm', 1.6),
  ('Conjunto Orquídea', 'Fecho Sutiã', 1.0),
  ('Conjunto Orquídea', 'Fio overlock', 0.015),
  ('Conjunto Orquídea', 'Forro', 0.0018),
  ('Conjunto Orquídea', 'Pino tag', 1.0),
  ('Conjunto Orquídea', 'Linha', 0.02),
  ('Conjunto Orquídea', 'Renda', 2.2),
  ('Encanto', 'Elástico Viés 16 mm', 1.2),
  ('Encanto', 'Fio overlock', 0.015),
  ('Encanto', 'Forro', 0.0018),
  ('Encanto', 'Pino tag', 1.0),
  ('Encanto', 'Linha', 0.02),
  ('Encanto', 'Microfibra de Poliamida', 0.051),
  ('Paixão', 'Elástico primavera', 0.35),
  ('Paixão', 'Elástico Viés 16 mm', 0.7),
  ('Paixão', 'Elástico Viés 25 mm', 0.35),
  ('Paixão', 'Fio overlock', 0.015),
  ('Paixão', 'Forro', 0.0018),
  ('Paixão', 'Linha', 0.02),
  ('Paixão', 'Pino tag', 1.0),
  ('Paixão', 'Renda', 0.6),
  ('Body Sedução', 'Alça de sutiã pronta', 2.0),
  ('Body Sedução', 'Elástico Viés 16 mm', 1.5),
  ('Body Sedução', 'Fio overlock', 0.015),
  ('Body Sedução', 'Forro', 0.0018),
  ('Body Sedução', 'Pino tag', 1.0),
  ('Body Sedução', 'Linha', 0.02),
  ('Body Sedução', 'Microfibra de Poliamida', 0.004),
  ('Body Sedução', 'Renda', 3.2),
  ('Chamego', 'Fio overlock', 0.015),
  ('Chamego', 'Forro', 0.0018),
  ('Chamego', 'Pino tag', 1.0),
  ('Chamego', 'Linha', 0.02),
  ('Chamego', 'Microfibra de Poliamida', 0.06),
  ('Sonho', 'Alça de sutiã pronta', 2.0),
  ('Sonho', 'Elástico Viés 16 mm', 0.35),
  ('Sonho', 'Fio overlock', 0.015),
  ('Sonho', 'Forro', 0.002),
  ('Sonho', 'Pino tag', 1.0),
  ('Sonho', 'Linha', 0.02),
  ('Sonho', 'Renda Neon', 0.62),
  ('Alegria', 'Alça de sutiã pronta', 2.0),
  ('Alegria', 'Elástico primavera', 0.25),
  ('Alegria', 'Elástico Viés 16 mm', 0.9),
  ('Alegria', 'Fio overlock', 0.015),
  ('Alegria', 'Forro', 0.0015),
  ('Alegria', 'Linha', 0.02),
  ('Alegria', 'Microfibra de Poliamida', 0.006),
  ('Alegria', 'Pino tag', 1.0),
  ('Alegria', 'Renda Neon', 0.2),
  ('Daniella', 'Elástico Viés 16 mm', 0.5),
  ('Daniella', 'Fio overlock', 0.015),
  ('Daniella', 'Forro', 0.0015),
  ('Daniella', 'Pino tag', 1.0),
  ('Daniella', 'Linha', 0.02),
  ('Daniella', 'Suede', 0.042),
  ('Daniella', 'Renda 5 cm', 0.7),
  ('Bella', 'Elástico Viés 25 mm', 0.8),
  ('Bella', 'Elástico Viés 16 mm', 0.7),
  ('Bella', 'Suede', 0.042),
  ('Bella', 'Forro', 0.0018),
  ('Bella', 'Pino tag', 1.0),
  ('Bella', 'Linha', 0.02),
  ('Bella', 'Fio overlock', 0.015),
  ('Conjunto Lírio', 'Alça de sutiã pronta', 2.0),
  ('Conjunto Lírio', 'Arco', 2.0),
  ('Conjunto Lírio', 'Bojo Casca', 1.0),
  ('Conjunto Lírio', 'Elástico primavera', 0.17),
  ('Conjunto Lírio', 'Elástico Taquara', 0.5),
  ('Conjunto Lírio', 'Elástico Viés 16 mm', 2.2),
  ('Conjunto Lírio', 'Elástico Viés 25 mm', 0.9),
  ('Conjunto Lírio', 'Fecho Sutiã', 1.0),
  ('Conjunto Lírio', 'Fio overlock', 0.01),
  ('Conjunto Lírio', 'Forro', 0.004),
  ('Conjunto Lírio', 'Pino tag', 1.0),
  ('Conjunto Lírio', 'Linha', 0.016),
  ('Conjunto Lírio', 'Renda com fio dourado', 0.65),
  ('Conjunto Lírio', 'Tule', 0.029),
  ('Conjunto Tulipa', 'Renda com fio dourado', 1.25),
  ('Conjunto Tulipa', 'Alça de sutiã pronta', 2.0),
  ('Conjunto Tulipa', 'Elástico Taquara', 0.55),
  ('Conjunto Tulipa', 'Elástico primavera', 0.5),
  ('Conjunto Tulipa', 'Arco', 2.0),
  ('Conjunto Tulipa', 'Microfibra de Poliamida', 0.025),
  ('Conjunto Tulipa', 'Linha', 0.05),
  ('Conjunto Tulipa', 'Fio overlock', 0.03),
  ('Conjunto Tulipa', 'Pino tag', 1.0),
  ('Conjunto Tulipa', 'Elástico Viés 25 mm', 0.8),
  ('Conjunto Tulipa', 'Elástico Viés 16 mm', 0.6),
  ('Márcia', 'Elástico Viés 16 mm', 0.8),
  ('Márcia', 'Elástico Viés 25 mm', 0.7),
  ('Márcia', 'Rendão', 0.0191),
  ('Márcia', 'Linha', 0.02),
  ('Márcia', 'Fio overlock', 0.015),
  ('Márcia', 'Pino tag', 1.0),
  ('Márcia', 'Forro', 0.002),
  ('Bianca', 'Elástico Viés 16 mm', 2.0),
  ('Bianca', 'Rendão', 0.016),
  ('Bianca', 'Linha', 0.02),
  ('Bianca', 'Fio overlock', 0.015),
  ('Bianca', 'Pino tag', 1.0),
  ('Bianca', 'Forro', 0.002),
  ('Núvem', 'Argola', 3.0),
  ('Núvem', 'Elástico Viés 16 mm', 2.0),
  ('Núvem', 'Fio overlock', 0.015),
  ('Núvem', 'Forro', 0.002),
  ('Núvem', 'Pino tag', 1.0),
  ('Núvem', 'Linha', 0.02),
  ('Núvem', 'Rendão', 0.0065),
  ('Cristal', 'Elástico Viés 25 mm', 0.44),
  ('Cristal', 'Elástico Viés 16 mm', 0.62),
  ('Cristal', 'Alça de sutiã pronta', 2.0),
  ('Cristal', 'Pino tag', 1.0),
  ('Cristal', 'Microfibra de Poliamida', 0.018),
  ('Cristal', 'Linha', 0.02),
  ('Cristal', 'Fio overlock', 0.015),
  ('Cristal', 'Forro', 0.002),
  ('Turquesa', 'Elástico Savana 15mm', 0.4),
  ('Turquesa', 'Microfibra de Poliamida', 0.02),
  ('Turquesa', 'Elástico Viés 16 mm', 1.3),
  ('Turquesa', 'Linha', 0.02),
  ('Turquesa', 'Fio overlock', 0.015),
  ('Turquesa', 'Pino tag', 1.0),
  ('Turquesa', 'Forro', 0.002),
  ('Carinho', 'Fio overlock', 0.015),
  ('Carinho', 'Forro', 0.0018),
  ('Carinho', 'Pino tag', 1.0),
  ('Carinho', 'Linha', 0.02),
  ('Carinho', 'Microfibra de Poliamida', 0.065),
  ('Amor', 'Alça de coraçãozinho', 2.0),
  ('Amor', 'Elástico Viés 16 mm', 1.15),
  ('Amor', 'Fio overlock', 0.015),
  ('Amor', 'Forro', 0.0015),
  ('Amor', 'Linha', 0.02),
  ('Amor', 'Tule', 0.005),
  ('Amor', 'Pino tag', 1.0),
  ('Desejo', 'Alça de coraçãozinho', 2.0),
  ('Desejo', 'Elástico primavera', 0.2),
  ('Desejo', 'Elástico Viés 16 mm', 0.7),
  ('Desejo', 'Forro', 0.0018),
  ('Desejo', 'Renda', 0.5),
  ('Desejo', 'Pino tag', 1.0),
  ('Ana', 'Elástico Viés 16 mm', 0.7),
  ('Ana', 'Elástico Viés 25 mm', 0.66),
  ('Ana', 'Fio overlock', 0.015),
  ('Ana', 'Forro', 0.0015),
  ('Ana', 'Linha', 0.02),
  ('Ana', 'Microfibra de Poliamida', 0.031),
  ('Ana', 'Pino tag', 1.0),
  ('Kamila', 'Elástico Viés 16 mm', 1.0),
  ('Kamila', 'Elástico Viés 25 mm', 0.7),
  ('Kamila', 'Fio overlock', 0.015),
  ('Kamila', 'Forro', 0.0038),
  ('Kamila', 'Linha', 0.02),
  ('Kamila', 'Microfibra de Poliamida', 0.025),
  ('Kamila', 'Pino tag', 1.0),
  ('Coração', 'Alça de coraçãozinho', 2.0),
  ('Coração', 'Elástico Viés 16 mm', 0.9),
  ('Coração', 'Fio overlock', 0.015),
  ('Coração', 'Forro', 0.002),
  ('Coração', 'Linha', 0.02),
  ('Coração', 'Renda', 0.2),
  ('Coração', 'Pino tag', 1.0),
  ('Núbia', 'Elástico Viés 25 mm', 0.7),
  ('Núbia', 'Fio overlock', 0.015),
  ('Núbia', 'Forro', 0.0018),
  ('Núbia', 'Linha', 0.02),
  ('Núbia', 'Microfibra de Poliamida', 0.043),
  ('Núbia', 'Pino tag', 1.0),
  ('Meirinha', 'Fio overlock', 0.015),
  ('Meirinha', 'Forro', 0.0049),
  ('Meirinha', 'Linha', 0.02),
  ('Meirinha', 'Microfibra de Poliamida', 0.04),
  ('Meirinha', 'Pino tag', 1.0),
  ('Natália', 'Elástico Viés 16 mm', 1.2),
  ('Natália', 'Elástico Viés 25 mm', 0.7),
  ('Natália', 'Fio overlock', 0.015),
  ('Natália', 'Forro', 0.0036),
  ('Natália', 'Linha', 0.02),
  ('Natália', 'Microfibra de Poliamida', 0.024),
  ('Natália', 'Pino tag', 1.0),
  ('Laura Suede', 'Elástico Viés 16 mm', 1.2),
  ('Laura Suede', 'Elástico Viés 25 mm', 0.8),
  ('Laura Suede', 'Fio overlock', 0.015),
  ('Laura Suede', 'Forro', 0.0018),
  ('Laura Suede', 'Linha', 0.02),
  ('Laura Suede', 'Suede', 0.035),
  ('Laura Suede', 'Pino tag', 1.0),
  ('Charme', 'Fio overlock', 0.015),
  ('Charme', 'Forro', 0.0019),
  ('Charme', 'Linha', 0.02),
  ('Charme', 'Microfibra de Poliamida', 0.038),
  ('Charme', 'Elástico Viés 16 mm', 0.56),
  ('Charme', 'Pino tag', 1.0),
  ('Eclipse', 'Renda', 0.2),
  ('Eclipse', 'Elástico Viés 25 mm', 1.12),
  ('Eclipse', 'Forro', 0.002),
  ('Eclipse', 'Linha', 0.02),
  ('Eclipse', 'Fio overlock', 0.015),
  ('Eclipse', 'Laço grande', 1.0),
  ('Eclipse', 'Pino tag', 1.0),
  ('Eclipse', 'Elástico primavera', 0.19),
  ('Safira', 'Microfibra de Poliamida', 0.01971),
  ('Safira', 'Elástico Viés 16 mm', 0.19),
  ('Safira', 'Elástico Savana 15mm', 0.4),
  ('Safira', 'Forro', 0.0018),
  ('Safira', 'Linha', 0.02),
  ('Safira', 'Fio overlock', 0.015),
  ('Safira', 'Pino tag', 1.0),
  ('Cupido', 'Renda', 0.2),
  ('Cupido', 'Elástico Viés 16 mm', 1.2),
  ('Cupido', 'Elástico primavera', 0.19),
  ('Cupido', 'Forro', 0.002),
  ('Cupido', 'Linha', 0.02),
  ('Cupido', 'Fio overlock', 0.015),
  ('Cupido', 'Coração passante triplo', 1.0),
  ('Selvagem', 'Renda', 0.2),
  ('Selvagem', 'Elástico Viés 16 mm', 1.2),
  ('Selvagem', 'Elástico primavera', 0.19),
  ('Selvagem', 'Forro', 0.002),
  ('Selvagem', 'Linha', 0.02),
  ('Selvagem', 'Fio overlock', 0.015),
  ('Selvagem', 'Coelho passante triplo', 1.0),
  ('Atrevida', 'Alça de coraçãozinho', 2.0),
  ('Atrevida', 'Coração Faz o Pix', 1.0),
  ('Atrevida', 'Elástico Viés 16 mm', 0.9),
  ('Atrevida', 'Fio overlock', 0.015),
  ('Atrevida', 'Forro', 0.002),
  ('Atrevida', 'Linha', 0.02),
  ('Atrevida', 'Renda', 0.2)
) v(modelo, insumo, consumo)
join modelos m on lower(m.nome) = lower(v.modelo)
join insumos i on i.nome = v.insumo
on conflict (modelo_id, insumo_id) do update set consumo = excluded.consumo;

commit;
